### ISSUE TITLE
Feature request: Drag and drop downloaded file to Windows File Explorer

### ISSUE THREAD

**Issue by syldub69** [aesqe/firefox-downloads-sidebar#10]
It would be great to be able to drag and drop the downloaded file to Windows File Explorer with support of SHIFT (move) or CRTL (copy).
I mean, to provide the same feature as the Firefox download windows:
![image](https://user-images.githubusercontent.com/16567425/37013102-6de45960-20f8-11e8-8aa4-e0b0939e7053.png)

**Comment by josalhor** [comment]
Hi,

I've answered a similar question here: https://github.com/aesqe/firefox-downloads-sidebar/issues/10

But your question is focused on the WFE. So even if the current limitation of the CSP was removed, I don't think it would be possible to access the low level that it requires to make it feature possible.

It would require dragging not to the browser, to the desktop. Which doesn't seems possible.

Not only that, even if dragging at that level was available, you would need to call a file movement or / copy and have the ability to do so at any folder in the system, not some kind of local, limited by an API, thing.

So I'm sorry to say this is not possible. Especially because I really want this feature myself.

**Comment by aesqe** [comment]
Unfortunately, no, it's currently not possible, for security reasons.

**Comment by aesqe** [comment]
Actually, I might have closed this too soon, there is a section about this here: https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API/Recommended_drag_types#filestoos

I'll try to test it out this weekend.

**Comment by aesqe** [comment]
I've finally had some time to try this out. Unfortunately, these are old docs for XPCOM add-ons. Web extensions don't have the needed interfaces for this, yet.
