### ISSUE TITLE
Downloads display

### ISSUE THREAD

**Issue by rayman89** [aesqe/firefox-downloads-sidebar#2]
Seems that now the addon is displaying the popup menu thing that appears when you press the native firefox downloads button. Could you make it so that it displays about:downloads instead? Currently there is a bug and every time you restart the browser the popup that shows the downloads gets cleared but about:downloads does not so I think it would be better to show that. Also like a guy on amo reviews says it would be nice to have the right click options on the sidebar as well like copy the url of the download clean the downloads etc.

**Comment by aesqe** [comment]
@rayman could you explain that first part a bit more, about the popup menu?

Unfortunately, I can't just display about:downloads in the sidebar, it doesn't work if I put it in an iframe (probably a security issue).

The clearing of the downloads is not a bug, it's how the latest downloads are implemented. As far as I can tell, extensions don't have access to the complete list of downloads, just those started in the current session. The moment you close Firefox, those downloads are no longer awailable.

Right-click menu is a bit more... fiddly to implement, because the default page context menu items are always visible, I can't hide them. I'll see if it makes more sense appending options to the right-click menu, or to a custom dropdown.

**Comment by rayman89** [comment]
![imagen](https://user-images.githubusercontent.com/5449042/34181934-cd7eab60-e4d9-11e7-8c0e-caf6a858254f.png)

That's the popup thing I mention.  The clearing of that info was reported in bugzilla and it's being discussed.

**Comment by aesqe** [comment]
v0.4:
* Added the clear all downloads, copy download link, open download page buttons;
* reworked the download progress management;
* added the browser action (toolbar) button

**Comment by rayman89** [comment]
Thanks a lot its looking great now. I wish It would show all the previous downloads as well not only the current session ones. Would that be possible sometime?

**Comment by aesqe** [comment]
@rayman89 unfortunately, as far as I can determine - no :/ It seems that the downloads API is limited to session downloads only.

**Comment by rayman89** [comment]
Would the fix of this "bug" make it able to get the info from previous sessions? 
https://bugzilla.mozilla.org/show_bug.cgi?id=1255507

**Comment by aesqe** [comment]
@rayman89 Yes, I believe so 👍
