### ISSUE TITLE
Retried downloads in progress do not show progress in sidebar

### ISSUE THREAD

**Issue by xpaulnim** [aesqe/firefox-downloads-sidebar#22]
When I retry a download in the regular firefox download window, the sidebar does not update to show that the retried download is now in progress. In the attached screenshot, the zip file is in progress in the downloads window but not in the sidebar.
![Annotation 2020-05-19 144626](https://user-images.githubusercontent.com/8648705/82334538-0727e300-99e0-11ea-8a0c-d66203ab8acc.png)

Also, it would be nice to have an option to retry a download.

**Comment by josalhor** [comment]
¡Thanks for the report!
I'll take a crack at it after I finish my exams

**Comment by josalhor** [comment]
Hi!

I am very sorry I never got to reply to this issue. I have stopped using this extension because the lack of drag and drop is really frustrating. I did, however, fix this issue (or at least I remember I did) a few months ago here: https://github.com/josalhor/firefox-downloads-sidebar/commit/5a94dfb5248710f992a6cb6d2765d7f4e4ee8cd1.

**Comment by xpaulnim** [comment]
Neat. I don't mind the lack of drag and drop. But I prefer it to the default one.
Thanks for this btw
